name: VeilGuard
version: 1.0.0
main: com.veilguard.VeilGuard
api-version: 1.16
depend: [ProtocolLib]
commands:
  veilguard:
    description: VeilGuard main command
    usage: /<command> [args]
    permission: veilguard.admin
